import type { AppRole, Permission } from "@/types/auth";

export const rolePermissions: Record<AppRole, Permission[]> = {
  technical_owner: [
    "admin:access",
    "system:monitoring",
    "settings:manage",
    "commercial_settings:manage",
    "users:manage",
    "roles:assign",
    "audit:read",
    "invoices:read",
    "invoices:correct",
    "invoices:manage",
    "reports:read",
    "reports:export",
  ],
  admin: [
    "admin:access",
    "products:manage",
    "inventory:manage",
    "orders:manage",
    "customers:read",
    "payments:read",
    "payments:manage",
    "invoices:read",
    "invoices:create",
    "invoices:correct",
    "invoices:manage",
    "fiscal:read",
    "crm:manage",
    "reports:read",
    "reports:export",
    "settings:manage",
    "commercial_settings:manage",
    "users:manage",
    "roles:assign",
    "audit:read",
    "system:monitoring",
  ],
  business_owner: [
    "admin:access",
    "products:manage",
    "inventory:manage",
    "orders:manage",
    "customers:read",
    "customers:manage",
    "payments:read",
    "payments:manage",
    "invoices:read",
    "invoices:create",
    "invoices:correct",
    "invoices:manage",
    "fiscal:read",
    "crm:manage",
    "reports:read",
    "reports:export",
    "users:manage",
    "roles:assign",
    "audit:read",
    "commercial_settings:manage",
  ],
  vendedor: ["admin:access", "products:read", "orders:manage", "customers:manage", "crm:manage", "reports:read"],
  bodega: ["admin:access", "products:read", "inventory:manage", "shipments:manage", "orders:read"],
  contadora: [
    "admin:access",
    "orders:read",
    "customers:read",
    "payments:read",
    "invoices:read",
    "invoices:create",
    "invoices:correct",
    "fiscal:read",
    "reports:read",
    "reports:export",
  ],
  soporte: ["admin:access", "customers:read", "crm:manage", "orders:read", "invoices:read"],
  cliente: ["store:buy", "orders:read_own", "invoices:read_own"],
};

export function roleHasPermission(role: AppRole, permission: Permission) {
  return rolePermissions[role].includes(permission);
}
