"use client";
import type { ReactNode } from "react";
import { useEffect, useEffectEvent, useRef } from "react";
import { X } from "lucide-react";

export function AccessibleSheet({title,description,onClose,children,footer,returnFocusId}:{title:string;description?:string;onClose:()=>void;children:ReactNode;footer?:ReactNode;returnFocusId?:string}){
  const panel=useRef<HTMLDivElement>(null);const close=useRef<HTMLButtonElement>(null);const restore=useRef<HTMLElement|null>(null);const closeSheet=useEffectEvent(onClose);
  useEffect(()=>{restore.current=document.activeElement as HTMLElement;const previousOverflow=document.body.style.overflow;document.body.style.overflow="hidden";close.current?.focus();const node=panel.current;function key(event:KeyboardEvent){if(event.key==="Escape"){event.preventDefault();closeSheet();return}if(event.key!=="Tab"||!node)return;const focusable=Array.from(node.querySelectorAll<HTMLElement>('button:not([disabled]),a[href],input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])'));if(!focusable.length)return;const first=focusable[0],last=focusable[focusable.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}document.addEventListener("keydown",key);return()=>{const captured=restore.current;document.removeEventListener("keydown",key);document.body.style.overflow=previousOverflow;requestAnimationFrame(()=>{const explicit=returnFocusId?document.getElementById(returnFocusId):null;(explicit??captured)?.focus()})}},[returnFocusId]);
  return <div className="fixed inset-0 z-50 flex justify-end bg-black/45" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><div ref={panel} role="dialog" aria-modal="true" aria-labelledby="sheet-title" aria-describedby={description?"sheet-description":undefined} className="flex h-dvh w-full flex-col bg-white shadow-2xl sm:max-w-xl lg:max-w-2xl"><header className="flex items-start justify-between gap-4 border-b p-4 sm:p-5"><div><h2 id="sheet-title" className="text-xl font-bold">{title}</h2>{description?<p id="sheet-description" className="mt-1 text-sm text-black/55">{description}</p>:null}</div><button ref={close} type="button" onClick={onClose} className="grid size-11 shrink-0 place-items-center rounded-lg border" aria-label="Cerrar"><X size={20}/></button></header><div className="min-h-0 flex-1 overflow-y-auto p-4 sm:p-5">{children}</div>{footer?<footer className="sticky bottom-0 border-t bg-white p-4 shadow-[0_-8px_20px_rgba(0,0,0,.05)]">{footer}</footer>:null}</div></div>}
