"use client";

/* eslint-disable react-hooks/set-state-in-effect -- authenticated report data follows explicit filter state */
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState, type ReactNode } from "react";
import { AlertTriangle, CheckCircle2, CircleDollarSign, Clock3, LoaderCircle, RefreshCw, ShoppingCart, XCircle } from "lucide-react";
import type { SellerCommercialListItem } from "@/types/commissions";
import type { CommercialDashboardData, CommercialFilters } from "@/types/commercial-reporting";

const currency = new Intl.NumberFormat("es-HN", { style: "currency", currency: "HNL" });
const dateText = new Intl.DateTimeFormat("es-HN", { dateStyle: "medium", timeZone: "America/Tegucigalpa" });

function initialFilters(sellerId?: string): CommercialFilters {
  const now = new Date();
  const from = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), 1));
  return { from: from.toISOString().slice(0, 10), to: now.toISOString().slice(0, 10), sellerId: sellerId ?? null, channel: "all", customerType: "all", paymentMethod: "all", saleStatus: "all", specialPrice: "all", comparePrevious: false };
}

export function CommercialReportsDashboardV2({ sellerId }: { sellerId?: string }) {
  const [filters, setFilters] = useState(() => initialFilters(sellerId));
  const [data, setData] = useState<CommercialDashboardData | null>(null);
  const [sellers, setSellers] = useState<SellerCommercialListItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [message, setMessage] = useState("");
  const [offset, setOffset] = useState(0);
  const load = useCallback(async () => {
    setLoading(true); setMessage("");
    const params = new URLSearchParams({ ...Object.fromEntries(Object.entries(filters).map(([key, value]) => [key, String(value ?? "")])), limit: "20", offset: String(offset) });
    try {
      const response = await fetch(`/api/admin/commercial-reports?${params}`, { cache: "no-store" });
      const body = (await response.json()) as CommercialDashboardData & { message?: string };
      if (!response.ok) throw new Error(body.message);
      setData(body);
    } catch (error) { setMessage(error instanceof Error ? error.message : "No se pudo cargar el reporte."); }
    finally { setLoading(false); }
  }, [filters, offset]);
  useEffect(() => void load(), [load]);
  useEffect(() => {
    if (sellerId) return;
    fetch("/api/admin/commission-sellers?limit=50", { cache: "no-store" }).then((response) => response.json()).then((body: { results?: SellerCommercialListItem[] }) => setSellers(body.results ?? [])).catch(() => setSellers([]));
  }, [sellerId]);
  const set = <K extends keyof CommercialFilters>(key: K, value: CommercialFilters[K]) => { setFilters((current) => ({ ...current, [key]: value })); setOffset(0); };
  const maxTrend = useMemo(() => Math.max(1, ...(data?.trend.map((item) => Math.max(item.sold, item.collected)) ?? [])), [data]);
  const profile = data?.sellers[0];
  return <div className="space-y-3">
    <header className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-2xl font-bold">{sellerId ? profile?.sellerName ?? "Análisis del vendedor" : "Reportes comerciales"}</h2><p className="text-sm text-black/55">Ventas, cobros, vendedores, comisiones y comportamiento comercial reconciliados.</p></div><div className="flex gap-2"><Link href="/admin/centro-reportes" className="min-h-11 rounded-lg border bg-white px-4 py-3 text-sm font-semibold">Generar reporte</Link><button onClick={() => void load()} disabled={loading} aria-busy={loading || undefined} className="grid size-11 place-items-center rounded-lg border bg-white disabled:opacity-55" aria-label={loading ? "Actualizando reporte" : "Actualizar reporte"}><RefreshCw aria-hidden size={18} className={loading ? "animate-spin motion-reduce:animate-none" : ""} /></button></div></header>
    <section aria-label="Filtros del reporte" className="grid gap-2 rounded-xl border bg-white p-3 shadow-sm sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-5">
      <Filter label="Desde"><input type="date" value={filters.from} onChange={(event) => set("from", event.target.value)} /></Filter>
      <Filter label="Hasta"><input type="date" value={filters.to} onChange={(event) => set("to", event.target.value)} /></Filter>
      {!sellerId ? <Filter label="Vendedor"><select value={filters.sellerId ?? ""} onChange={(event) => set("sellerId", event.target.value || null)}><option value="">Todos</option>{sellers.map((seller) => <option key={seller.sellerId} value={seller.sellerId}>{seller.name}</option>)}</select></Filter> : null}
      <Filter label="Canal"><select value={filters.channel} onChange={(event) => set("channel", event.target.value as CommercialFilters["channel"])}><option value="all">Todos</option><option value="pos">POS</option><option value="web">Web</option></select></Filter>
      <Filter label="Tipo de cliente"><select value={filters.customerType} onChange={(event) => set("customerType", event.target.value as CommercialFilters["customerType"])}><option value="all">Todos</option><option value="retail">Minorista</option><option value="wholesale">Mayorista</option></select></Filter>
      <Filter label="Método de pago"><select value={filters.paymentMethod} onChange={(event) => set("paymentMethod", event.target.value as CommercialFilters["paymentMethod"])}><option value="all">Todos</option><option value="cash">Efectivo</option><option value="card">Tarjeta</option><option value="bank_transfer">Transferencia</option><option value="commercial_credit">Crédito comercial</option></select></Filter>
      <Filter label="Estado"><select value={filters.saleStatus} onChange={(event) => set("saleStatus", event.target.value as CommercialFilters["saleStatus"])}><option value="all">Todas</option><option value="valid">Válidas</option><option value="cancelled">Canceladas</option></select></Filter>
      <Filter label="Precio especial"><select value={filters.specialPrice} onChange={(event) => set("specialPrice", event.target.value as CommercialFilters["specialPrice"])}><option value="all">Todos</option><option value="with">Con precio especial</option><option value="without">Sin precio especial</option></select></Filter>
      <label className="flex min-h-11 items-center gap-3 rounded-lg border px-3 text-sm font-semibold sm:self-end"><input type="checkbox" checked={filters.comparePrevious} onChange={(event) => set("comparePrevious", event.target.checked)} className="size-5" />Comparar período anterior</label>
    </section>
    {message ? <p role="alert" className="rounded-lg bg-red-50 p-3 text-red-800">{message}</p> : null}
    {loading && data ? <p role="status" aria-live="polite" className="rounded-lg bg-red-50 px-3 py-2 text-sm font-semibold text-[#b91c25]">Actualizando reporte comercial…</p> : null}
    {loading && !data ? <div className="grid min-h-96 place-items-center rounded-xl border bg-white" role="status" aria-live="polite"><span className="inline-flex items-center gap-2"><LoaderCircle aria-hidden className="animate-spin motion-reduce:animate-none" />Cargando reporte comercial…</span></div> : data ? <>
      <section className="grid grid-cols-2 gap-2 lg:grid-cols-3 xl:grid-cols-6"><Kpi label="Ventas realizadas" value={String(data.kpis.sales)} icon={ShoppingCart} /><Kpi label="Monto vendido" value={currency.format(data.kpis.sold)} icon={CircleDollarSign} /><Kpi label="Cobrado" value={currency.format(data.kpis.collected)} icon={CheckCircle2} green /><Kpi label="Pendiente" value={currency.format(data.kpis.outstanding)} icon={Clock3} amber /><Kpi label="Ticket promedio" value={currency.format(data.kpis.averageTicket)} icon={CircleDollarSign} /><Kpi label="Canceladas" value={String(data.kpis.cancelled)} icon={XCircle} red /></section>
      {data.previous ? <PreviousComparison current={data.kpis} previous={data.previous} /> : null}
      {sellerId ? <SellerSummary data={data} /> : <GlobalSummary data={data} maxTrend={maxTrend} />}
      <SalesTable data={data} sellerId={sellerId} />
      <footer className="flex items-center justify-between text-sm"><span>{data.totalSales} ventas</span><div className="flex gap-2"><button disabled={offset === 0} onClick={() => setOffset(Math.max(0, offset - 20))} className="min-h-11 rounded-lg border px-3 disabled:opacity-40">Anterior</button><button disabled={offset + data.sales.length >= data.totalSales} onClick={() => setOffset(offset + 20)} className="min-h-11 rounded-lg border px-3 disabled:opacity-40">Siguiente</button></div></footer>
    </> : null}
  </div>;
}

function Filter({ label, children }: { label: string; children: ReactNode }) { return <label className="text-xs font-semibold [&_input]:mt-1 [&_input]:min-h-11 [&_input]:w-full [&_input]:rounded-lg [&_input]:border [&_input]:px-3 [&_select]:mt-1 [&_select]:min-h-11 [&_select]:w-full [&_select]:rounded-lg [&_select]:border [&_select]:px-3 [&_select]:text-sm">{label}{children}</label>; }
function Kpi({ label, value, icon: Icon, green, amber, red }: { label: string; value: string; icon: typeof ShoppingCart; green?: boolean; amber?: boolean; red?: boolean }) { return <article className="rounded-xl border bg-white p-4 shadow-sm"><div className="flex items-start gap-3"><span className={`grid size-10 shrink-0 place-items-center rounded-full ${green ? "bg-emerald-50 text-emerald-700" : amber ? "bg-amber-50 text-amber-700" : red ? "bg-red-50 text-red-700" : "bg-blue-50 text-blue-700"}`}><Icon size={20} /></span><div className="min-w-0"><p className="text-xs text-black/50">{label}</p><strong className="break-words text-lg">{value}</strong></div></div></article>; }
function PreviousComparison({ current, previous }: { current: CommercialDashboardData["kpis"]; previous: CommercialDashboardData["kpis"] }) { return <Card title="Comparación con el período anterior"><div className="grid gap-2 sm:grid-cols-3"><Comparison label="Ventas" value={current.sales} previous={previous.sales} /><Comparison label="Monto vendido" value={current.sold} previous={previous.sold} money /><Comparison label="Cobrado" value={current.collected} previous={previous.collected} money /></div></Card>; }
function Comparison({ label, value, previous, money }: { label: string; value: number; previous: number; money?: boolean }) { const format = (amount: number) => money ? currency.format(amount) : String(amount); const delta = previous ? ((value - previous) / previous) * 100 : null; return <div className="rounded-lg bg-slate-50 p-3 text-sm"><span className="text-black/55">{label}</span><strong className="mt-1 block text-lg">{format(value)}</strong><span className="text-xs text-black/50">Anterior: {format(previous)}</span>{delta !== null ? <span className={`ml-2 text-xs font-semibold ${delta >= 0 ? "text-emerald-700" : "text-red-700"}`}>{delta >= 0 ? "+" : ""}{delta.toFixed(1)}%</span> : null}</div>; }

function GlobalSummary({ data, maxTrend }: { data: CommercialDashboardData; maxTrend: number }) { return <>
  <section className="grid gap-3 xl:grid-cols-[1fr_1.35fr_.85fr]"><Card title="Evolución de ventas"><div className="flex h-52 items-end gap-1 overflow-hidden" role="img" aria-label="Gráfico de monto vendido y cobrado por fecha">{data.trend.map((item) => <div key={item.date} className="flex min-w-6 flex-1 items-end justify-center gap-0.5" title={`${item.date}: vendido ${currency.format(item.sold)}, cobrado ${currency.format(item.collected)}`}><span className="w-2 rounded-t bg-red-500" style={{ height: `${Math.max(3, item.sold / maxTrend * 100)}%` }} /><span className="w-2 rounded-t bg-emerald-500" style={{ height: `${Math.max(3, item.collected / maxTrend * 100)}%` }} /></div>)}{!data.trend.length ? <p className="m-auto text-sm text-black/45">Sin datos en el período.</p> : null}</div><p className="mt-2 text-xs text-black/45">Rojo: vendido · Verde: cobrado</p></Card><Card title="Ventas por vendedor"><div className="divide-y">{data.sellers.slice(0, 6).map((row) => <div key={row.sellerId ?? row.sellerName} className="grid grid-cols-[1fr_auto] gap-3 py-3 text-sm"><div><strong>{row.sellerName}</strong><span className="block text-xs text-black/45">{row.sales} ventas · {currency.format(row.collected)} cobrado</span></div>{row.sellerId ? <Link href={`/admin/reportes-comerciales/vendedores/${row.sellerId}`} className="min-h-11 px-2 py-3 font-semibold text-blue-700">Analizar</Link> : null}</div>)}</div></Card><Card title="Cobros y saldos"><p className="text-2xl font-bold text-emerald-700">{currency.format(data.kpis.collected)}</p><div className="mt-3 h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-emerald-600" style={{ width: `${Math.min(100, data.kpis.sold ? data.kpis.collected / data.kpis.sold * 100 : 0)}%` }} /></div><p className="mt-2 text-sm">Pendiente: <strong className="text-amber-700">{currency.format(data.kpis.outstanding)}</strong></p></Card></section>
  <section className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Breakdown title="Tipo de venta" rows={data.customerTypes} /><Breakdown title="Métodos de pago" rows={data.paymentMethods} /><Breakdown title="Canal de ventas" rows={data.channels} /><Card title="Comisiones"><DataLine label="Potencial" value={currency.format(data.commissions.potential)} /><DataLine label="Ganada" value={currency.format(data.commissions.earned)} green /><DataLine label="Por ganar" value={currency.format(data.commissions.remaining)} amber /><DataLine label="Revertida" value={currency.format(data.commissions.reversed)} /></Card><Card title="Precios especiales"><DataLine label="Solicitudes" value={String(data.specialPrices.requests)} /><DataLine label="Aprobadas" value={String(data.specialPrices.approved)} green /><DataLine label="Utilizadas" value={String(data.specialPrices.used)} /><DataLine label="Monto vendido" value={currency.format(data.specialPrices.soldAmount)} /></Card><Card title="Cancelaciones y reversiones"><DataLine label="Ventas canceladas" value={String(data.kpis.cancelled)} /><DataLine label="Monto cancelado" value={currency.format(data.kpis.cancelledAmount)} /><DataLine label="Comisión revertida" value={currency.format(data.commissions.reversed)} /></Card></section>
  <section className="grid gap-3 lg:grid-cols-[1.2fr_.8fr]"><Card title="Requiere atención"><div className="divide-y">{data.attention.map((item) => <Link key={item.code} href={item.href} className="flex min-h-12 items-center justify-between gap-3 py-2 text-sm"><span className="flex items-center gap-2"><AlertTriangle className="text-amber-600" size={17} />{item.label}</span><strong>{item.count}{item.amount ? ` · ${currency.format(item.amount)}` : ""}</strong></Link>)}</div></Card><Card title="Cobertura de reglas"><strong className="text-2xl">{data.coverage.withRule} de {data.coverage.activeSellers}</strong><p className="text-sm text-black/50">vendedores activos con regla vigente</p><div className="mt-3 h-3 rounded-full bg-slate-100"><div className="h-full rounded-full bg-emerald-600" style={{ width: `${data.coverage.percentage}%` }} /></div><p className="mt-2 text-sm font-semibold text-emerald-700">{data.coverage.percentage}%</p></Card></section>
</>; }
function SellerSummary({ data }: { data: CommercialDashboardData }) { const seller = data.sellers[0]; const detail = data.sellerDetail; return <section className="grid gap-3 lg:grid-cols-2 xl:grid-cols-4"><Card title="Comisiones del período"><DataLine label="Potencial" value={currency.format(seller?.potential ?? 0)} /><DataLine label="Ganada" value={currency.format(seller?.earned ?? 0)} green /><DataLine label="Por ganar" value={currency.format(seller?.remaining ?? 0)} amber /><DataLine label="Revertida" value={currency.format(seller?.reversed ?? 0)} /></Card><Card title="Clientes atendidos"><DataLine label="Clientes únicos" value={String(detail?.customersAttended ?? 0)} /><DataLine label="Minoristas" value={String(detail?.retailCustomers ?? 0)} /><DataLine label="Mayoristas" value={String(detail?.wholesaleCustomers ?? 0)} /><DataLine label="Precios especiales" value={String(data.specialPrices.used)} /></Card><Card title="Cancelaciones y atribución"><DataLine label="Cancelaciones" value={String(detail?.cancellations ?? 0)} /><DataLine label="Monto cancelado" value={currency.format(detail?.cancelledAmount ?? 0)} /><DataLine label="Comisión revertida" value={currency.format(detail?.reversedCommission ?? 0)} /><DataLine label="Correcciones de atribución" value={String(detail?.attributionCorrections ?? 0)} /></Card><Card title="Historial de reglas"><div className="divide-y">{detail?.ruleHistory.slice(0, 4).map((rule) => <div key={rule.ruleId} className="py-2 text-sm"><div className="flex justify-between gap-2"><strong>Versión {rule.version}</strong><span>{rule.type === "PERCENTAGE" ? `${rule.value}%` : currency.format(rule.value)}</span></div><p className="text-xs text-black/45">{dateText.format(new Date(rule.effectiveFrom))}{rule.policyName ? ` · ${rule.policyName}` : ""}</p></div>)}{!detail?.ruleHistory.length ? <p className="text-sm text-black/45">Sin reglas configuradas.</p> : null}</div><Link href="/admin/vendedores" className="mt-3 inline-flex min-h-11 items-center font-semibold text-blue-700">Ver perfil completo</Link></Card></section>; }
function SalesTable({ data, sellerId }: { data: CommercialDashboardData; sellerId?: string }) { return <section className="overflow-hidden rounded-xl border bg-white shadow-sm"><h3 className="border-b p-4 font-bold">Ventas del período</h3><div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[980px] text-sm"><thead className="bg-slate-50 text-left text-xs"><tr>{["Fecha", "Venta", "Vendedor", "Cliente", "Tipo", "Total", "Cobrado", "Pendiente", "Precio especial", "Comisión"].map((heading) => <th key={heading} className="px-3 py-3">{heading}</th>)}</tr></thead><tbody>{data.sales.map((row) => <tr key={row.orderId} className="border-t"><td className="px-3 py-3">{dateText.format(new Date(row.date))}</td><td className="px-3 font-semibold">{row.orderNumber}</td><td className="px-3">{row.sellerName}</td><td className="px-3">{row.customerName}</td><td className="px-3">{row.customerType === "wholesale" ? "Mayorista" : "Minorista"}</td><td className="px-3 font-semibold">{currency.format(row.total)}</td><td className="px-3 text-emerald-700">{currency.format(row.collected)}</td><td className="px-3 text-amber-700">{currency.format(row.outstanding)}</td><td className="px-3">{row.specialPrice ? "Sí" : "No"}</td><td className="px-3">{currency.format(row.earned)}</td></tr>)}</tbody></table></div><div className="divide-y md:hidden">{data.sales.map((row) => <article key={row.orderId} className="p-4"><div className="flex justify-between gap-3"><strong>{row.orderNumber}</strong><strong>{currency.format(row.total)}</strong></div><p className="mt-1 text-sm">{row.customerName}{sellerId ? "" : ` · ${row.sellerName}`}</p><div className="mt-2 grid grid-cols-2 gap-2 text-xs"><span>Cobrado <strong className="block text-emerald-700">{currency.format(row.collected)}</strong></span><span>Pendiente <strong className="block text-amber-700">{currency.format(row.outstanding)}</strong></span></div></article>)}</div>{!data.sales.length ? <p className="p-8 text-center text-sm text-black/45">No hay ventas para estos filtros.</p> : null}</section>; }
function Card({ title, children }: { title: string; children: ReactNode }) { return <article className="rounded-xl border bg-white p-4 shadow-sm"><h3 className="mb-3 font-bold">{title}</h3>{children}</article>; }
function DataLine({ label, value, green, amber }: { label: string; value: string; green?: boolean; amber?: boolean }) { return <div className="flex justify-between gap-3 py-1.5 text-sm"><span>{label}</span><strong className={green ? "text-emerald-700" : amber ? "text-amber-700" : ""}>{value}</strong></div>; }
function Breakdown({ title, rows }: { title: string; rows: CommercialDashboardData["paymentMethods"] }) { const total = rows.reduce((sum, row) => sum + row.amount, 0); return <Card title={title}>{rows.map((row) => <div key={row.key} className="py-1.5 text-sm"><div className="flex justify-between"><span>{row.label}</span><strong>{currency.format(row.amount)}</strong></div><div className="mt-1 h-2 rounded bg-slate-100"><div className="h-full rounded bg-blue-600" style={{ width: `${total ? row.amount / total * 100 : 0}%` }} /></div></div>)}{!rows.length ? <p className="text-sm text-black/45">Sin datos.</p> : null}</Card>; }
