"use client";

import { useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Plus, Save, Search, Trash2 } from "lucide-react";
import { cancelInventoryAdjustmentAction, confirmInventoryAdjustmentAction, saveInventoryAdjustmentDraftAction, searchInventoryAdjustmentProductsAction } from "@/app/admin/inventario/ajustes/actions";
import { InventoryAdjustmentConfirmDialog } from "@/components/admin/inventory-adjustment-confirm-dialog";
import { useToast } from "@/contexts/toast-context";
import type { InventoryAdjustmentDirection, InventoryAdjustmentProduct, InventoryAdjustmentReason } from "@/types/inventory-adjustments";

type DraftLine = { product: InventoryAdjustmentProduct; direction: InventoryAdjustmentDirection; quantity: number; reason: InventoryAdjustmentReason; detail: string; unitCost?: number };
const increaseReasons: Array<[InventoryAdjustmentReason,string]> = [["physical_count_surplus","Sobrante en conteo físico"],["recovery","Recuperación"],["operational_error","Error operativo"],["other","Otro"]];
const decreaseReasons: Array<[InventoryAdjustmentReason,string]> = [["physical_count_shortage","Faltante en conteo físico"],["damage_or_shrinkage","Daño o merma"],["loss","Pérdida"],["operational_error","Error operativo"],["other","Otro"]];

export function InventoryAdjustmentBuilder({ today, canCost, canConfirm }: { today: string; canCost: boolean; canConfirm: boolean }) {
  const router=useRouter(); const toast=useToast(); const [pending,startTransition]=useTransition();
  const [requestKey] = useState(() => globalThis.crypto.randomUUID()); const [adjustmentId,setAdjustmentId]=useState<string>(); const [version,setVersion]=useState(1);
  const [reference,setReference]=useState(""); const [notes,setNotes]=useState(""); const [lines,setLines]=useState<DraftLine[]>([]);
  const [query,setQuery]=useState(""); const [results,setResults]=useState<InventoryAdjustmentProduct[]>([]); const [searching,setSearching]=useState(false); const [dialog,setDialog]=useState(false);
  const totals=useMemo(()=>lines.reduce((sum,line)=>({increase:sum.increase+(line.direction==="increase"?line.quantity:0),decrease:sum.decrease+(line.direction==="decrease"?line.quantity:0),cost:sum.cost+(line.quantity*(line.unitCost??line.product.cost_price??0))}),{increase:0,decrease:0,cost:0}),[lines]);
  function searchProducts(){startTransition(async()=>{setSearching(true);const r=await searchInventoryAdjustmentProductsAction(query);setSearching(false);if(r.ok)setResults(r.items);else toast.error(r.message??"No se pudo buscar.");});}
  function addProduct(product: InventoryAdjustmentProduct){if(lines.some(l=>l.product.id===product.id)){toast.warning("El producto ya está incluido.");return;}if(lines.length>=100){toast.error("El máximo es 100 productos.");return;}setLines(c=>[...c,{product,direction:"increase",quantity:1,reason:"physical_count_surplus",detail:"",unitCost:product.cost_price}]);setResults([]);setQuery("");}
  function updateLine(index:number, patch:Partial<DraftLine>){setLines(c=>c.map((line,i)=>i===index?{...line,...patch}:line));}
  function payload(){return {requestKey,adjustmentId,expectedVersion:version,effectiveDate:today,reference,notes,lines:lines.map(l=>({product_id:l.product.id,direction:l.direction,quantity:l.quantity,reason_code:l.reason,reason_detail:l.detail,unit_cost:l.direction==="increase"&&canCost?l.unitCost:undefined}))};}
  async function save(){const r=await saveInventoryAdjustmentDraftAction(payload());if(r.ok){setAdjustmentId(r.id);setVersion(r.version??version);toast.success(r.message);}else toast.error(r.message);return r;}
  function saveDraft(){startTransition(async()=>{await save();});}
  function confirm(){startTransition(async()=>{const saved=await save();if(!saved.ok||!saved.id)return;const r=await confirmInventoryAdjustmentAction(saved.id,saved.version??version,requestKey);if(!r.ok){toast.error(r.message);setDialog(false);return;}toast.success(r.message);router.push(`/admin/inventario/ajustes/${r.id}`);});}
  function cancelDraft(){if(!adjustmentId)return;startTransition(async()=>{const r=await cancelInventoryAdjustmentAction(adjustmentId,version);if(r.ok){toast.success(r.message);router.push("/admin/inventario/ajustes");}else toast.error(r.message);});}
  return <div className="space-y-5">
    <section className="rounded-xl border border-black/10 bg-white p-4 sm:p-5"><div className="grid gap-4 md:grid-cols-2"><label><span className="mb-1 block text-sm font-medium">Bodega</span><input value="Bodega principal — Inventario general" readOnly className="min-h-11 w-full rounded-lg border border-black/10 bg-[#f4f4f5] px-3 text-sm"/></label><label><span className="mb-1 block text-sm font-medium">Fecha efectiva</span><input type="date" value={today} readOnly className="min-h-11 w-full rounded-lg border border-black/10 bg-[#f4f4f5] px-3"/></label><label><span className="mb-1 block text-sm font-medium">Referencia <span className="font-normal text-black/45">(opcional)</span></span><input value={reference} maxLength={160} onChange={e=>setReference(e.target.value)} className="min-h-11 w-full rounded-lg border border-black/15 px-3" placeholder="Conteo, acta o incidencia"/></label><label><span className="mb-1 block text-sm font-medium">Observación <span className="font-normal text-black/45">(opcional)</span></span><textarea value={notes} maxLength={2000} onChange={e=>setNotes(e.target.value)} className="min-h-24 w-full rounded-lg border border-black/15 p-3"/></label></div></section>
    <section className="rounded-xl border border-black/10 bg-white p-4 sm:p-5"><h2 className="text-lg font-semibold">Agregar productos</h2><p className="mt-1 text-sm text-black/55">Busque por SKU, código, nombre o marca. Máximo 100 productos.</p><form onSubmit={e=>{e.preventDefault();searchProducts();}} className="mt-4 flex flex-col gap-2 sm:flex-row"><label className="sr-only" htmlFor="adjustment-product-search">Buscar producto</label><div className="relative flex-1"><Search aria-hidden size={17} className="absolute left-3 top-3.5 text-black/40"/><input id="adjustment-product-search" role="combobox" aria-expanded={results.length>0} aria-controls="adjustment-products-list" value={query} onChange={e=>setQuery(e.target.value)} className="min-h-11 w-full rounded-lg border border-black/15 pl-10 pr-3" placeholder="SKU, código, nombre o marca"/></div><button type="submit" disabled={pending||searching} className="min-h-11 rounded-lg bg-black px-5 font-semibold text-white">{searching?"Buscando…":"Buscar"}</button></form>
      {results.length>0?<ul id="adjustment-products-list" role="listbox" className="mt-2 max-h-72 overflow-y-auto rounded-lg border border-black/10 bg-white p-1 shadow-lg">{results.map(p=><li key={p.id} role="option" aria-selected="false"><button type="button" onClick={()=>addProduct(p)} className="flex min-h-14 w-full items-center justify-between gap-3 rounded-md px-3 py-2 text-left hover:bg-[#f4f4f5] focus-visible:outline-2"><span className="min-w-0"><span className="block break-words font-medium">{p.name}</span><span className="text-xs text-black/50">{p.sku} · {p.brand}</span></span><span className="shrink-0 text-sm">Disp. {p.available_stock}</span></button></li>)}</ul>:null}
    </section>
    <section className="overflow-hidden rounded-xl border border-black/10 bg-white"><div className="flex items-center justify-between border-b border-black/10 p-4 sm:p-5"><div><h2 className="text-lg font-semibold">Productos del ajuste</h2><p className="text-sm text-black/50">{lines.length}/100 líneas</p></div><Plus aria-hidden/></div>
      {lines.length===0?<p className="p-6 text-sm text-black/50">Aún no ha agregado productos.</p>:<div className="grid gap-3 p-3 lg:hidden">{lines.map((line,index)=><LineCard key={line.product.id} line={line} index={index} canCost={canCost} onUpdate={updateLine} onDelete={()=>setLines(c=>c.filter((_,i)=>i!==index))}/>)}</div>}
      {lines.length>0?<div className="hidden overflow-x-auto lg:block"><table className="w-full min-w-[1040px] text-left text-sm"><thead className="bg-[#e7e5e4] text-xs uppercase text-black/55"><tr>{["Producto","Existencias","Tipo","Cantidad","Motivo","Costo","Después","Acción"].map(h=><th key={h} className="px-3 py-3">{h}</th>)}</tr></thead><tbody className="divide-y divide-black/10">{lines.map((line,index)=><LineRow key={line.product.id} line={line} index={index} canCost={canCost} onUpdate={updateLine} onDelete={()=>setLines(c=>c.filter((_,i)=>i!==index))}/>)}</tbody></table></div>:null}
    </section>
    <section className="sticky bottom-3 z-20 flex flex-col gap-3 rounded-xl border border-black/10 bg-white/95 p-4 shadow-xl backdrop-blur sm:flex-row sm:items-center sm:justify-between"><p className="text-sm"><strong>{lines.length}</strong> productos · <span className="text-emerald-700">+{totals.increase}</span> · <span className="text-red-700">-{totals.decrease}</span>{canCost?` · L ${totals.cost.toLocaleString("es-HN",{minimumFractionDigits:2})}`:""}</p><div className="flex flex-col gap-2 sm:flex-row">{adjustmentId?<button type="button" onClick={cancelDraft} disabled={pending} className="min-h-11 rounded-lg border border-red-200 px-4 font-semibold text-red-700">Cancelar borrador</button>:null}<button type="button" onClick={saveDraft} disabled={pending||!lines.length} className="min-h-11 rounded-lg border border-black/15 px-4 font-semibold"><Save aria-hidden size={17} className="mr-2 inline"/>{pending?"Guardando…":"Guardar borrador"}</button>{canConfirm?<button type="button" onClick={()=>setDialog(true)} disabled={pending||!lines.length} className="min-h-11 rounded-lg bg-black px-5 font-semibold text-white">Revisar y confirmar</button>:null}</div></section>
    {dialog?<InventoryAdjustmentConfirmDialog pending={pending} onCancel={()=>setDialog(false)} onConfirm={confirm} summary={{date:today,lines:lines.length,increases:totals.increase,decreases:totals.decrease,reference,notes,total:canCost?totals.cost:undefined}}/>:null}
  </div>;
}

function reasonOptions(direction:InventoryAdjustmentDirection){return direction==="increase"?increaseReasons:decreaseReasons;}
function preview(line:DraftLine){return line.product.stock+(line.direction==="increase"?line.quantity:-line.quantity);}
function LineFields({line,index,canCost,onUpdate}:{line:DraftLine;index:number;canCost:boolean;onUpdate:(i:number,p:Partial<DraftLine>)=>void}){const invalid=preview(line)<line.product.reserved_stock;return <><label><span className="mb-1 block text-xs font-medium uppercase text-black/50">Tipo</span><select value={line.direction} onChange={e=>{const direction=e.target.value as InventoryAdjustmentDirection;onUpdate(index,{direction,reason:direction==="increase"?"physical_count_surplus":"physical_count_shortage"});}} className="min-h-11 w-full rounded-lg border border-black/15 px-2"><option value="increase">Incrementar</option><option value="decrease">Disminuir</option></select></label><label><span className="mb-1 block text-xs font-medium uppercase text-black/50">Cantidad</span><input type="number" min={1} max={1000000} step={1} value={line.quantity} aria-invalid={!Number.isInteger(line.quantity)||line.quantity<1||invalid} onChange={e=>onUpdate(index,{quantity:Number(e.target.value)})} className="min-h-11 w-full rounded-lg border border-black/15 px-3"/></label><label><span className="mb-1 block text-xs font-medium uppercase text-black/50">Motivo</span><select value={line.reason} onChange={e=>onUpdate(index,{reason:e.target.value as InventoryAdjustmentReason})} className="min-h-11 w-full rounded-lg border border-black/15 px-2">{reasonOptions(line.direction).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>{line.reason==="other"?<label><span className="mb-1 block text-xs font-medium uppercase text-black/50">Detalle requerido</span><input value={line.detail} maxLength={240} aria-invalid={!line.detail.trim()} onChange={e=>onUpdate(index,{detail:e.target.value})} className="min-h-11 w-full rounded-lg border border-black/15 px-3"/></label>:null}{canCost&&line.direction==="increase"?<label><span className="mb-1 block text-xs font-medium uppercase text-black/50">Costo unitario</span><input type="number" min="0.01" step="0.01" value={line.unitCost??""} onChange={e=>onUpdate(index,{unitCost:Number(e.target.value)})} className="min-h-11 w-full rounded-lg border border-black/15 px-3"/></label>:null}{invalid?<p role="alert" className="text-sm text-red-700">La disminución dejaría el stock por debajo de las {line.product.reserved_stock} unidades reservadas.</p>:null}</>}
function LineCard({line,index,canCost,onUpdate,onDelete}:{line:DraftLine;index:number;canCost:boolean;onUpdate:(i:number,p:Partial<DraftLine>)=>void;onDelete:()=>void}){return <article className="rounded-lg border border-black/10 p-4"><div className="flex justify-between gap-3"><div><h3 className="font-semibold">{line.product.name}</h3><p className="text-xs text-black/50">{line.product.sku}{!line.product.active?" · Producto inactivo":""}</p></div><button type="button" aria-label={`Eliminar ${line.product.name}`} onClick={onDelete} className="flex size-11 items-center justify-center rounded-lg border border-black/10 text-red-700"><Trash2 aria-hidden size={18}/></button></div><dl className="my-3 grid grid-cols-3 gap-2 text-sm"><Stat label="Stock" value={line.product.stock}/><Stat label="Reservado" value={line.product.reserved_stock}/><Stat label="Disponible" value={line.product.available_stock}/></dl><div className="grid gap-3 sm:grid-cols-2"><LineFields line={line} index={index} canCost={canCost} onUpdate={onUpdate}/><div className="rounded-lg bg-[#f4f4f5] p-3"><span className="text-xs uppercase text-black/50">Después (previo)</span><strong className="mt-1 block text-xl">{preview(line)}</strong></div></div></article>}
function LineRow({line,index,canCost,onUpdate,onDelete}:{line:DraftLine;index:number;canCost:boolean;onUpdate:(i:number,p:Partial<DraftLine>)=>void;onDelete:()=>void}){return <tr className="align-top"><td className="px-3 py-3"><strong className="block max-w-52 break-words">{line.product.name}</strong><span className="text-xs text-black/50">{line.product.sku}{!line.product.active?" · Inactivo":""}</span></td><td className="px-3 py-3">{line.product.stock} / {line.product.reserved_stock} / {line.product.available_stock}</td><td colSpan={4} className="px-3 py-3"><div className="grid grid-cols-4 gap-2"><LineFields line={line} index={index} canCost={canCost} onUpdate={onUpdate}/></div></td><td className="px-3 py-3 font-semibold">{preview(line)}</td><td className="px-3 py-3"><button type="button" aria-label={`Eliminar ${line.product.name}`} onClick={onDelete} className="flex size-11 items-center justify-center rounded-lg border border-black/10 text-red-700"><Trash2 aria-hidden size={18}/></button></td></tr>}
function Stat({label,value}:{label:string;value:number}){return <div className="rounded-md bg-[#f8fafc] p-2"><dt className="text-xs text-black/45">{label}</dt><dd className="font-semibold">{value}</dd></div>}
