"use client";

/* eslint-disable react-hooks/set-state-in-effect -- authenticated server state is intentionally synchronized after navigation and generation */
import type { ReactElement } from "react";
import { useCallback, useEffect, useRef, useState } from "react";
import { CheckCircle2, Clock3, FileSpreadsheet, FileText, Plus, RotateCcw, XCircle } from "lucide-react";
import { AccessibleSheet } from "@/components/admin/accessible-sheet";
import { AsyncDownloadLink, Button } from "@/components/ui";
import { reportTypeLabels } from "@/lib/commercial-report-domain";
import type { SellerCommercialListItem } from "@/types/commissions";
import type { CommercialFilters, CommercialReportFormat, CommercialReportType, ReportGeneration, SavedReportConfiguration } from "@/types/commercial-reporting";

const pageSize = 10;
const allSections = ["summary", "details", "filters", "commissions", "specialPrices"];
const allColumns = ["date", "sale", "seller", "customer", "channel", "customerType", "paymentMethod", "status", "total", "collected", "outstanding", "specialPrice", "commission"];
const descriptions: Record<CommercialReportType, string> = {
  SELLER_SALES: "Ventas, montos, cobros, saldos, ticket y comisión por vendedor.",
  COMMISSIONS: "Potencial, ganada, por ganar, revertida y regla histórica.",
  SPECIAL_PRICES: "Solicitudes, decisiones y autorizaciones utilizadas.",
  OUTSTANDING_SALES: "Ventas con saldo pendiente, cliente y vendedor.",
  CUSTOMER_TYPES: "Distribución comercial minorista y mayorista.",
  PAYMENT_METHODS: "Distribución del total vendido por método de pago.",
  COMMERCIAL_SUMMARY: "Resumen general de ventas, cobros, comisiones y actividad.",
};

type History = { results: ReportGeneration[]; total: number; configurations: SavedReportConfiguration[] };
type ReportDraft = { type: CommercialReportType; format?: CommercialReportFormat; filters?: CommercialFilters; name?: string; sections?: string[]; columns?: string[] };

export function ReportCenterV2() {
  const [history, setHistory] = useState<History | null>(null);
  const [draft, setDraft] = useState<ReportDraft | null>(null);
  const [page, setPage] = useState(1);
  const [message, setMessage] = useState("");
  const [loadingHistory, setLoadingHistory] = useState(true);
  const load = useCallback(async () => {
    setLoadingHistory(true);
    try {
      const response = await fetch(`/api/admin/commercial-reports/history?limit=${pageSize}&offset=${(page - 1) * pageSize}`, { cache: "no-store" });
      const body = await response.json() as History & { message?: string };
      if (!response.ok) throw new Error(body.message);
      setHistory(body);
    } catch (error) { setMessage(error instanceof Error ? error.message : "No se pudo cargar el historial."); }
    finally { setLoadingHistory(false); }
  }, [page]);
  useEffect(() => { void load(); }, [load]);
  const pages = Math.max(1, Math.ceil((history?.total ?? 0) / pageSize));
  const openConfiguration = (config: SavedReportConfiguration) => setDraft({ type: config.reportType, format: config.format, filters: config.filters, name: config.name, sections: config.sections, columns: config.columns });

  return <div className="space-y-4">
    <header className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-2xl font-bold">Reportes disponibles</h2><p className="text-sm text-black/55">Genere documentos controlados con filtros y snapshots autorizados.</p></div><button onClick={() => setDraft({ type: "COMMERCIAL_SUMMARY" })} className="inline-flex min-h-11 items-center gap-2 rounded-lg bg-[#e4252c] px-4 font-semibold text-white"><Plus size={18} />Generar reporte</button></header>
    <section className="grid grid-cols-2 gap-2 lg:grid-cols-4"><Summary label="Reportes disponibles" value="7" icon={FileText} /><Summary label="Generados" value={String(history?.total ?? 0)} icon={CheckCircle2} /><Summary label="Configuraciones" value={String(history?.configurations.length ?? 0)} icon={FileSpreadsheet} /><Summary label="Último reporte" value={history?.results[0]?.generatedAt ? new Date(history.results[0].generatedAt).toLocaleDateString("es-HN") : "—"} icon={Clock3} /></section>
    <p className="rounded-xl border border-blue-200 bg-blue-50 p-3 text-sm text-blue-900"><strong>Los reportes respetan los filtros seleccionados.</strong> Las reglas históricas se leen del snapshot capturado al confirmar cada venta; nunca se recalculan con la regla actual.</p>
    <section className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{(Object.keys(reportTypeLabels) as CommercialReportType[]).map((type) => <article key={type} className="rounded-xl border bg-white p-4 shadow-sm"><span className="grid size-10 place-items-center rounded-full bg-blue-50 text-blue-700"><FileText size={20} /></span><h3 className="mt-3 font-bold">{reportTypeLabels[type]}</h3><p className="mt-1 min-h-10 text-sm text-black/55">{descriptions[type]}</p><button onClick={() => setDraft({ type })} className="mt-3 min-h-11 rounded-lg border border-red-200 px-4 text-sm font-semibold text-red-700">Generar</button></article>)}</section>
    {history?.configurations.length ? <section><h3 className="mb-2 text-lg font-bold">Configuraciones guardadas</h3><p className="mb-3 text-sm text-black/55">Al reutilizar una configuración se restauran formato, filtros y columnas; los datos se consultan nuevamente.</p><div className="grid gap-2 md:grid-cols-2 xl:grid-cols-3">{history.configurations.map((config) => <button key={config.configurationId} onClick={() => openConfiguration(config)} className="min-h-20 rounded-xl border bg-white p-4 text-left shadow-sm"><strong>{config.name}</strong><span className="mt-1 block text-xs text-black/45">{reportTypeLabels[config.reportType]} · {config.format}</span></button>)}</div></section> : null}
    <section className="overflow-hidden rounded-xl border bg-white shadow-sm" aria-busy={loadingHistory||undefined}><h3 className="border-b p-4 text-lg font-bold">Historial de reportes</h3>{loadingHistory?<p role="status" aria-live="polite" className="bg-red-50 px-4 py-2 text-sm font-semibold text-[#b91c25]">Actualizando historial…</p>:null}<div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[820px] text-sm"><thead className="bg-slate-50 text-left text-xs"><tr>{["Fecha", "Reporte", "Período", "Formato", "Generado por", "Estado", "Acción"].map((heading) => <th key={heading} className="px-3 py-3">{heading}</th>)}</tr></thead><tbody>{history?.results.map((row) => <tr key={row.generationId} className="border-t"><td className="px-3 py-3">{new Date(row.createdAt).toLocaleString("es-HN")}</td><td className="px-3 font-semibold">{row.reportName}</td><td className="px-3">{row.filters.from} – {row.filters.to}</td><td className="px-3">{row.format}</td><td className="px-3">{row.generatedByName}</td><td className="px-3"><Status value={row.status} /></td><td className="px-3"><HistoryAction row={row} retry={() => setDraft({ type: row.reportType, format: row.format, filters: row.filters, name: row.reportName })} /></td></tr>)}</tbody></table></div>
      <div className="divide-y md:hidden">{history?.results.map((row) => <article key={row.generationId} className="p-4"><div className="flex justify-between gap-2"><strong>{row.reportName}</strong><Status value={row.status} /></div><p className="mt-1 text-xs text-black/45">{row.filters.from} – {row.filters.to} · {row.format}</p><HistoryAction row={row} retry={() => setDraft({ type: row.reportType, format: row.format, filters: row.filters, name: row.reportName })} /></article>)}</div>
      {!history?.results.length ? <p className="p-8 text-center text-sm text-black/45">Aún no hay reportes generados.</p> : null}
      {history && history.total > pageSize ? <nav aria-label="Paginación del historial" className="flex items-center justify-center gap-3 border-t p-4"><button disabled={page === 1} onClick={() => setPage((current) => Math.max(1, current - 1))} className="min-h-11 rounded-lg border px-4 disabled:opacity-40">Anterior</button><span className="text-sm">Página {page} de {pages}</span><button disabled={page >= pages} onClick={() => setPage((current) => Math.min(pages, current + 1))} className="min-h-11 rounded-lg border px-4 disabled:opacity-40">Siguiente</button></nav> : null}
    </section>
    {message ? <p role="status" className="rounded-lg bg-blue-50 p-3 text-blue-900">{message}</p> : null}
    {draft ? <GenerateReport draft={draft} onClose={() => setDraft(null)} onGenerated={async () => { setDraft(null); setPage(1); setMessage("Reporte generado y descargado correctamente."); await load(); }} /> : null}
  </div>;
}

function Summary({ label, value, icon: Icon }: { label: string; value: string; icon: typeof FileText }) { return <article className="rounded-xl border bg-white p-4 shadow-sm"><div className="flex gap-3"><span className="grid size-10 place-items-center rounded-full bg-blue-50 text-blue-700"><Icon size={20} /></span><div><p className="text-xs text-black/45">{label}</p><strong className="text-xl">{value}</strong></div></div></article>; }
function Status({ value }: { value: ReportGeneration["status"] }) { return <span className={`inline-flex items-center gap-1 rounded-full px-2 py-1 text-xs font-semibold ${value === "READY" ? "bg-emerald-50 text-emerald-700" : value === "FAILED" ? "bg-red-50 text-red-700" : "bg-blue-50 text-blue-700"}`}>{value === "READY" ? <CheckCircle2 size={13} /> : value === "FAILED" ? <XCircle size={13} /> : <Clock3 size={13} />}{value === "READY" ? "Listo" : value === "FAILED" ? "Falló" : "Generando"}</span>; }
function HistoryAction({ row, retry }: { row: ReportGeneration; retry: () => void }) { if (row.status === "READY") return <AsyncDownloadLink href={`/api/admin/commercial-reports/${row.generationId}/download`} pendingLabel="Descargando reporte…" className="mt-2 px-2 py-3 font-semibold text-blue-700">Descargar</AsyncDownloadLink>; if (row.status === "FAILED") return <button onClick={retry} className="mt-2 inline-flex min-h-11 items-center gap-2 px-2 text-blue-700"><RotateCcw size={16} />Reintentar</button>; return <span className="inline-block py-3 text-black/45">—</span>; }
function defaultFilters(): CommercialFilters { const now = new Date(); const from = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), 1)); return { from: from.toISOString().slice(0, 10), to: now.toISOString().slice(0, 10), sellerId: null, channel: "all", customerType: "all", paymentMethod: "all", saleStatus: "all", specialPrice: "all", comparePrevious: false }; }

function GenerateReport({ draft, onClose, onGenerated }: { draft: ReportDraft; onClose: () => void; onGenerated: () => void }) {
  const [format, setFormat] = useState<CommercialReportFormat>(draft.format ?? "PDF");
  const [filters, setFilters] = useState<CommercialFilters>(draft.filters ?? defaultFilters());
  const [name, setName] = useState(draft.name ?? `${reportTypeLabels[draft.type]} — ${new Date().toLocaleDateString("es-HN", { month: "long", year: "numeric" })}`);
  const [sellers, setSellers] = useState<SellerCommercialListItem[]>([]);
  const [save, setSave] = useState(false); const [configName, setConfigName] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const busyRef = useRef(false);
  useEffect(() => { fetch("/api/admin/commission-sellers?limit=50", { cache: "no-store" }).then((response) => response.json()).then((body: { results?: SellerCommercialListItem[] }) => setSellers(body.results ?? [])).catch(() => setSellers([])); }, []);
  function setFilter<K extends keyof CommercialFilters>(key: K, value: CommercialFilters[K]) { setFilters((current) => ({ ...current, [key]: value })); }
  async function generate() { if (busyRef.current) return; busyRef.current = true; setBusy(true); setError(""); try { const response = await fetch("/api/admin/commercial-reports/generate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ requestKey: crypto.randomUUID(), reportType: draft.type, format, reportName: name, filters, sections: draft.sections ?? allSections, columns: draft.columns ?? allColumns, saveConfiguration: save, configurationName: configName }) }); if (!response.ok) { const body = await response.json() as { message?: string }; throw new Error(body.message ?? "No se pudo generar el reporte."); } const blob = await response.blob(); const found = /filename="([^"]+)"/.exec(response.headers.get("Content-Disposition") ?? ""); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = found?.[1] ?? `reporte.${format.toLowerCase()}`; anchor.click(); URL.revokeObjectURL(url); onGenerated(); } catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudo generar el reporte."); } finally { busyRef.current = false; setBusy(false); } }
  return <AccessibleSheet title="Generar reporte" description="Configure el alcance y formato. El servidor conservará el snapshot y la trazabilidad." onClose={()=>{if(!busy)onClose()}} footer={<div className="flex justify-end gap-2"><Button variant="ghost" onClick={onClose} disabled={busy}>Cancelar</Button><Button disabled={name.trim().length < 3 || Boolean(save && configName.trim().length < 3)} onClick={generate} pending={busy} pendingLabel={`Generando ${format}…`} aria-describedby="generation-requirements">Generar {format}</Button></div>}><div className="space-y-5">
    <section><span className="text-xs font-bold uppercase text-black/45">Tipo de reporte</span><p className="mt-1 text-lg font-bold">{reportTypeLabels[draft.type]}</p><p className="text-sm text-black/55">{descriptions[draft.type]}</p></section>
    <fieldset><legend className="text-sm font-semibold">Formato</legend><div className="mt-2 grid grid-cols-2 gap-2"><button type="button" aria-pressed={format === "PDF"} onClick={() => setFormat("PDF")} className={`min-h-20 rounded-xl border p-3 ${format === "PDF" ? "border-red-500 bg-red-50 text-red-700" : ""}`}><FileText className="mx-auto" /><strong className="mt-1 block">PDF</strong></button><button type="button" aria-pressed={format === "XLSX"} onClick={() => setFormat("XLSX")} className={`min-h-20 rounded-xl border p-3 ${format === "XLSX" ? "border-emerald-500 bg-emerald-50 text-emerald-700" : ""}`}><FileSpreadsheet className="mx-auto" /><strong className="mt-1 block">Excel</strong></button></div></fieldset>
    <section className="grid gap-3 sm:grid-cols-2"><Field label="Desde"><input type="date" value={filters.from} onChange={(event) => setFilter("from", event.target.value)} /></Field><Field label="Hasta"><input type="date" value={filters.to} onChange={(event) => setFilter("to", event.target.value)} /></Field><Field label="Vendedor"><select value={filters.sellerId ?? ""} onChange={(event) => setFilter("sellerId", event.target.value || null)}><option value="">Todos los vendedores</option>{sellers.map((seller) => <option key={seller.sellerId} value={seller.sellerId}>{seller.name}</option>)}</select></Field><Field label="Canal"><select value={filters.channel} onChange={(event) => setFilter("channel", event.target.value as CommercialFilters["channel"])}><option value="all">Todos</option><option value="pos">POS</option><option value="web">Web</option></select></Field><Field label="Tipo de cliente"><select value={filters.customerType} onChange={(event) => setFilter("customerType", event.target.value as CommercialFilters["customerType"])}><option value="all">Todos</option><option value="retail">Minorista</option><option value="wholesale">Mayorista</option></select></Field><Field label="Método de pago"><select value={filters.paymentMethod} onChange={(event) => setFilter("paymentMethod", event.target.value as CommercialFilters["paymentMethod"])}><option value="all">Todos</option><option value="cash">Efectivo</option><option value="card">Tarjeta</option><option value="bank_transfer">Transferencia</option><option value="commercial_credit">Crédito comercial</option></select></Field><Field label="Estado de venta"><select value={filters.saleStatus} onChange={(event) => setFilter("saleStatus", event.target.value as CommercialFilters["saleStatus"])}><option value="all">Todas</option><option value="valid">Válidas</option><option value="cancelled">Canceladas</option></select></Field><Field label="Precio especial"><select value={filters.specialPrice} onChange={(event) => setFilter("specialPrice", event.target.value as CommercialFilters["specialPrice"])}><option value="all">Todos</option><option value="with">Con precio especial</option><option value="without">Sin precio especial</option></select></Field></section>
    <label className="flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" checked={filters.comparePrevious} onChange={(event) => setFilter("comparePrevious", event.target.checked)} className="size-5" />Comparar con el período anterior</label>
    <p className="rounded-lg border border-blue-100 bg-blue-50 p-3 text-sm">Vista previa: período {filters.from} – {filters.to}, formato {format}. Máximo 5,000 filas; si se excede deberá acotar los filtros.</p>
    <label className="block text-sm font-semibold">Nombre del reporte<input value={name} onChange={(event) => setName(event.target.value)} maxLength={120} className="mt-1 min-h-11 w-full rounded-lg border px-3" /></label>
    <label className="flex min-h-11 items-start gap-3 text-sm"><input type="checkbox" checked={save} onChange={(event) => setSave(event.target.checked)} className="mt-1 size-5" /><span><strong className="block">Guardar configuración</strong>Guarda filtros y formato, nunca datos del reporte.</span></label>
    {save ? <label className="block text-sm font-semibold">Nombre de la configuración<input value={configName} onChange={(event) => setConfigName(event.target.value)} maxLength={100} className="mt-1 min-h-11 w-full rounded-lg border px-3" /></label> : null}
    <p id="generation-requirements" className="rounded-lg bg-slate-50 p-3 text-xs text-black/60"><strong>Trazabilidad:</strong> se registra actor, filtros normalizados, formato, estado, conteo y hash del snapshot. No se almacenan costos, márgenes ni archivos públicos.</p>{error ? <p role="alert" className="rounded-lg bg-red-50 p-3 text-red-800">{error}</p> : null}
  </div></AccessibleSheet>;
}

function Field({ label, children }: { label: string; children: ReactElement<{ className?: string }> }) { return <label className="text-sm font-semibold">{label}<span className="mt-1 block [&>*]:min-h-11 [&>*]:w-full [&>*]:rounded-lg [&>*]:border [&>*]:px-3">{children}</span></label>; }
