"use client";

import { useEffect, useRef, useState } from "react";
import { Edit3, LoaderCircle, Plus, Search, UserRound, X } from "lucide-react";
import type { PosCustomerContext, PosCustomerSearchResult } from "@/types/point-of-sale";

const emptyForm={contactName:"",phone:"",email:"",businessName:"",taxId:"",address:"",city:""};
export function SellerCustomers(){
  const [query,setQuery]=useState("");const [offset,setOffset]=useState(0);const [rows,setRows]=useState<PosCustomerSearchResult[]>([]);const [total,setTotal]=useState(0);const [loading,setLoading]=useState(true);const [message,setMessage]=useState("");
  const [editing,setEditing]=useState<PosCustomerContext|null|undefined>(undefined);const [form,setForm]=useState(emptyForm);const [saving,setSaving]=useState(false);const drawer=useRef<HTMLElement>(null);
  useEffect(()=>{const controller=new AbortController();const timer=setTimeout(async()=>{setLoading(true);try{const response=await fetch(`/api/admin/pos/customers/search?q=${encodeURIComponent(query)}&limit=15&offset=${offset}`,{cache:"no-store",signal:controller.signal});const payload=await response.json() as {results?:PosCustomerSearchResult[];total?:number;message?:string};if(!response.ok)throw new Error(payload.message);setRows(payload.results??[]);setTotal(payload.total??0);}catch(error){if(!controller.signal.aborted)setMessage(error instanceof Error?error.message:"No se pudieron cargar los clientes.");}finally{if(!controller.signal.aborted)setLoading(false);}},250);return()=>{clearTimeout(timer);controller.abort();};},[query,offset]);
  useEffect(()=>{if(editing===undefined)return;const previous=document.activeElement as HTMLElement|null;drawer.current?.querySelector<HTMLElement>("input, button")?.focus();function key(event:KeyboardEvent){if(event.key==="Escape")setEditing(undefined);if(event.key!=="Tab"||!drawer.current)return;const focusable=[...drawer.current.querySelectorAll<HTMLElement>('button:not([disabled]), input:not([disabled]), textarea:not([disabled]), select:not([disabled]), [tabindex]:not([tabindex="-1"])')];if(!focusable.length)return;const first=focusable[0];const last=focusable[focusable.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}document.addEventListener("keydown",key);return()=>{document.removeEventListener("keydown",key);previous?.focus()};},[editing]);
  function openNew(){setEditing(null);setForm(emptyForm);setMessage("");}
  async function openEdit(customer:PosCustomerSearchResult){setMessage("");const response=await fetch(`/api/admin/pos/customers/${customer.customerId}`,{cache:"no-store"});const payload=await response.json() as PosCustomerContext&{message?:string};if(!response.ok){setMessage(payload.message??"No se pudo cargar el cliente.");return;}setEditing(payload);setForm({contactName:payload.displayName,phone:payload.phone??"",email:payload.email??"",businessName:payload.businessName??"",taxId:payload.taxId??"",address:payload.address??"",city:payload.city??""});}
  async function save(){setSaving(true);setMessage("");const body={...form,requestKey:crypto.randomUUID(),commercialNotes:null,customerType:"retail",creditMode:"none",creditLimit:0,creditTermsDays:30,creditNotes:null,changeReason:"Actualizacion basica registrada por vendedor.",duplicateOverrideReason:null,...(editing?{expectedCommercialVersion:editing.commercialVersion}:{})};try{const response=await fetch(editing?`/api/admin/pos/customers/${editing.customerId}`:"/api/admin/pos/customers",{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const payload=await response.json() as {message?:string};if(!response.ok)throw new Error(payload.message);setEditing(undefined);setOffset(0);setQuery(value=>value+" ");setTimeout(()=>setQuery(value=>value.trim()),0);}catch(error){setMessage(error instanceof Error?error.message:"No se pudo guardar el cliente.");}finally{setSaving(false);}}
  return <div className="space-y-3"><header className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-2xl font-bold">Clientes</h2><p className="text-sm text-black/55">Identidad comercial basica para tus ventas.</p></div><button onClick={openNew} className="inline-flex min-h-11 items-center gap-2 rounded-lg bg-[#e4252c] px-4 font-semibold text-white"><Plus size={18}/>Nuevo cliente</button></header>
    <label className="block rounded-xl border bg-white p-3 text-sm font-semibold shadow-sm">Buscar clientes<span className="relative mt-2 block"><Search className="absolute left-3 top-3 text-black/35" size={18}/><input value={query} onChange={event=>{setQuery(event.target.value);setOffset(0);}} placeholder="Nombre, telefono o RTN" className="min-h-11 w-full rounded-lg border pl-10 pr-3 font-normal"/></span></label>{message?<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-800">{message}</p>:null}
    <section className="overflow-hidden rounded-xl border bg-white shadow-sm">{loading?<div className="flex min-h-48 items-center justify-center gap-2 text-black/50"><LoaderCircle className="animate-spin"/>Cargando...</div>:<div className="divide-y">{rows.map(customer=><article key={customer.customerId} className="grid gap-3 p-4 sm:grid-cols-[1fr_auto] sm:items-center"><div className="flex items-start gap-3"><span className="grid size-10 place-items-center rounded-full bg-emerald-50 text-emerald-700"><UserRound size={20}/></span><div><h3 className="font-semibold">{customer.displayName}</h3><p className="text-sm text-black/50">{customer.phoneMasked??"Sin telefono"} · {customer.emailMasked??"Sin correo"}</p><span className="mt-1 inline-flex rounded-full bg-slate-100 px-2 py-1 text-xs">{customer.customerType==="wholesale"?"Mayorista autorizado":"Minorista"}</span></div></div><button onClick={()=>void openEdit(customer)} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg border px-3 text-sm font-semibold"><Edit3 size={16}/>Editar datos basicos</button></article>)}{!rows.length?<p className="p-8 text-center text-sm text-black/50">No se encontraron clientes.</p>:null}</div>}</section>
    <footer className="flex items-center justify-between text-sm"><span>Mostrando {rows.length} de {total}</span><div className="flex gap-2"><button disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-15))} className="min-h-11 rounded-lg border px-3 disabled:opacity-40">Anterior</button><button disabled={offset+rows.length>=total} onClick={()=>setOffset(offset+15)} className="min-h-11 rounded-lg border px-3 disabled:opacity-40">Siguiente</button></div></footer>
    {editing!==undefined?<div className="fixed inset-0 z-50 flex justify-end bg-black/45" role="dialog" aria-modal="true" aria-labelledby="seller-customer-title"><section ref={drawer} className="flex h-full w-full max-w-lg flex-col bg-white shadow-2xl"><header className="flex items-center justify-between border-b p-4"><div><p className="text-xs text-black/50">Datos permitidos</p><h2 id="seller-customer-title" className="text-xl font-bold">{editing?"Editar cliente":"Nuevo cliente"}</h2></div><button onClick={()=>setEditing(undefined)} className="grid size-11 place-items-center rounded-lg" aria-label="Cerrar"><X/></button></header><div className="grid flex-1 content-start gap-4 overflow-y-auto p-4 sm:grid-cols-2">{([['contactName','Nombre o contacto','text'],['businessName','Empresa','text'],['phone','Telefono','tel'],['email','Correo','email'],['taxId','RTN','text'],['city','Ciudad','text'],['address','Direccion','text']] as const).map(([key,label,type])=><label key={key} className={key==='address'?"sm:col-span-2":""}><span className="text-sm font-semibold">{label}</span><input type={type} value={form[key]} onChange={event=>setForm({...form,[key]:event.target.value})} className="mt-1 min-h-11 w-full rounded-lg border px-3"/></label>)}<p className="rounded-lg bg-blue-50 p-3 text-xs text-blue-800 sm:col-span-2">Mayorista, credito, limite, notas sensibles y cuenta web no pueden modificarse desde esta vista.</p></div><footer className="sticky bottom-0 flex gap-2 border-t bg-white p-4"><button onClick={()=>setEditing(undefined)} className="min-h-11 flex-1 rounded-lg border font-semibold">Cancelar</button><button onClick={()=>void save()} disabled={saving} className="min-h-11 flex-1 rounded-lg bg-[#e4252c] font-semibold text-white disabled:opacity-50">{saving?"Guardando...":"Guardar datos basicos"}</button></footer></section></div>:null}
  </div>;
}
