"use client";

import Link from "next/link";
import { useState } from "react";
import {
  CheckCircle2, CircleDollarSign, Clock3, FileText, Package, Search,
  ShoppingCart, Tag, TrendingUp, UserRound, Users,
} from "lucide-react";
import type { SellerProduct, SellerWorkspace } from "@/types/commissions";
import { commissionStatusLabels } from "@/types/commissions";
import { formatCurrency } from "@/utils/pricing";

type CustomerResult = { customerId: string; displayName: string; phoneMasked: string; customerType: string };

function Metric({ label, value, helper, tone = "blue" }: { label: string; value: string; helper: string; tone?: "blue" | "green" | "amber" | "red" }) {
  const colors={blue:"bg-blue-50 text-blue-700",green:"bg-emerald-50 text-emerald-700",amber:"bg-amber-50 text-amber-700",red:"bg-red-50 text-red-700"};
  const Icon=tone==="green"?CheckCircle2:tone==="amber"?Clock3:tone==="red"?TrendingUp:CircleDollarSign;
  return <article className="min-w-0 rounded-xl border border-black/10 bg-white p-3 shadow-sm"><div className="flex items-center gap-3"><span className={`grid size-10 shrink-0 place-items-center rounded-full ${colors[tone]}`}><Icon size={20}/></span><div className="min-w-0"><p className="text-xs text-black/55">{label}</p><p className="truncate text-lg font-bold">{value}</p></div></div><p className="mt-2 text-xs text-black/45">{helper}</p></article>;
}

function Status({ text, tone="green" }: { text:string;tone?:"green"|"amber"|"red" }) { const cls=tone==="green"?"bg-emerald-50 text-emerald-800":tone==="amber"?"bg-amber-50 text-amber-800":"bg-red-50 text-red-800";return <span className={`inline-flex rounded-full px-2 py-1 text-xs font-semibold ${cls}`}>{text}</span>; }

export function SellerWorkspaceDashboard({ data }: { data: SellerWorkspace }) {
  const [customerQuery,setCustomerQuery]=useState("");const [customers,setCustomers]=useState<CustomerResult[]>([]);const [customerBusy,setCustomerBusy]=useState(false);
  const [productQuery,setProductQuery]=useState("");const [products,setProducts]=useState<SellerProduct[]>([]);const [productBusy,setProductBusy]=useState(false);
  async function searchCustomers(){setCustomerBusy(true);try{const response=await fetch(`/api/admin/pos/customers/search?q=${encodeURIComponent(customerQuery)}&limit=4`,{cache:"no-store"});const payload=await response.json() as {results?:CustomerResult[]};setCustomers(response.ok?payload.results??[]:[]);}finally{setCustomerBusy(false);}}
  async function searchProducts(){setProductBusy(true);try{const response=await fetch(`/api/admin/seller-products?q=${encodeURIComponent(productQuery)}&limit=4`,{cache:"no-store"});const payload=await response.json() as {results?:SellerProduct[]};setProducts(response.ok?payload.results??[]:[]);}finally{setProductBusy(false);}}
  const rule=data.commission.currentRule;
  return <main className="mx-auto w-full max-w-[1680px] space-y-3 px-3 py-4 sm:px-5 lg:px-6">
    <header className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-bold">Panel de ventas</h1><p className="text-sm text-black/55">Tu actividad comercial y herramientas de trabajo.</p></div><div className="flex gap-2"><Link href="/admin/mis-ventas" className="inline-flex min-h-11 items-center gap-2 rounded-lg border bg-white px-4 font-semibold"><FileText size={18}/>Mis ventas</Link><Link href="/admin/pos" className="inline-flex min-h-11 items-center gap-2 rounded-lg bg-[#e4252c] px-4 font-semibold text-white"><ShoppingCart size={18}/>Nueva venta</Link></div></header>
    <section aria-label="Accesos rapidos" className="grid gap-2 sm:grid-cols-2 xl:grid-cols-4">
      {[["Nueva venta","Registrar una venta en el Punto de Venta.","/admin/pos",ShoppingCart],["Mis ventas","Consultar ventas, facturas y cobros.","/admin/mis-ventas",FileText],["Clientes","Buscar o registrar clientes.","/admin/clientes",Users],["Productos","Consultar precios y disponibilidad.","/admin/productos",Package]].map(([title,description,href,Icon])=><Link key={String(title)} href={String(href)} className="flex min-h-24 items-center gap-3 rounded-xl border border-black/10 bg-white p-4 shadow-sm transition hover:border-red-300"><span className="grid size-11 place-items-center rounded-full bg-red-50 text-red-600"><Icon size={21}/></span><span><strong className="block">{String(title)}</strong><span className="text-sm text-black/55">{String(description)}</span></span></Link>)}
    </section>
    <section className="rounded-xl border border-black/10 bg-white p-3 shadow-sm"><h2 className="mb-3 font-semibold">Mi rendimiento comercial</h2><div className="grid grid-cols-2 gap-2 lg:grid-cols-4 xl:grid-cols-7"><Metric label="Ventas de hoy" value={String(data.summary.todaySales)} helper="Ventas confirmadas" tone="green"/><Metric label="Monto hoy" value={formatCurrency(data.summary.todaySold)} helper="Confirmado hoy"/><Metric label="Ventas del mes" value={String(data.summary.monthSales)} helper="Sin canceladas" tone="green"/><Metric label="Monto del mes" value={formatCurrency(data.summary.monthSold)} helper="Ventas elegibles"/><Metric label="Cobrado" value={formatCurrency(data.summary.collected)} helper="Este mes" tone="green"/><Metric label="Pendiente" value={formatCurrency(data.summary.outstanding)} helper="Saldo de ventas" tone="amber"/><Metric label="Ticket promedio" value={formatCurrency(data.summary.averageTicket)} helper="Este mes"/></div></section>
    <section className="rounded-xl border border-black/10 bg-white p-3 shadow-sm"><div className="flex items-center justify-between gap-3"><h2 className="font-semibold">Mi comision</h2><Link href="/admin/mi-comision" className="text-sm font-semibold text-blue-700">Ver historial</Link></div><div className="mt-3 grid grid-cols-2 gap-2 lg:grid-cols-4 xl:grid-cols-[repeat(4,minmax(0,1fr))_1.5fr]"><Metric label="Comision potencial" value={formatCurrency(data.commission.potential)} helper="Este mes"/><Metric label="Comision ganada" value={formatCurrency(data.commission.earned)} helper="Segun cobros" tone="green"/><Metric label="Por ganar" value={formatCurrency(data.commission.remaining)} helper="Cobro pendiente" tone="amber"/><Metric label="Comision revertida" value={formatCurrency(data.commission.reversed)} helper="Este mes" tone="red"/><article className="rounded-xl border border-black/10 bg-slate-50 p-3"><p className="text-xs text-black/55">Regla vigente</p><strong className="mt-1 block">{rule?rule.type==="PERCENTAGE"?`${rule.value}% sobre ventas elegibles`:`${formatCurrency(rule.value)} por venta elegible`:"Sin regla configurada"}</strong><p className="mt-2 text-xs text-black/50">Mercaderia elegible antes de ISV. Se gana conforme se reciben cobros validos.</p></article></div></section>
    <section className="grid items-start gap-3 xl:grid-cols-[1.05fr_1fr_.95fr]">
      <div className="space-y-3"><article className="rounded-xl border border-black/10 bg-white p-3 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-semibold">Borradores abiertos</h2><Status text={`${data.drafts.length} visibles`}/></div><div className="mt-2 divide-y">{data.drafts.map(draft=><div key={draft.draftId} className="flex items-center justify-between gap-3 py-3"><div><strong className="block text-sm">{draft.customerName}</strong><span className="text-xs text-black/50">{draft.itemCount} productos · {formatCurrency(draft.total)}</span></div><Link href={`/admin/pos?draftId=${draft.draftId}`} className="inline-flex min-h-11 items-center rounded-lg border border-red-300 px-3 text-sm font-semibold text-red-700">Continuar</Link></div>)}{!data.drafts.length?<p className="py-5 text-center text-sm text-black/45">No tienes borradores abiertos.</p>:null}</div></article>
      <article className="rounded-xl border border-black/10 bg-white p-3 shadow-sm"><h2 className="font-semibold">Ultimas ventas</h2><div className="mt-2 divide-y">{data.recentSales.map(sale=><Link key={sale.orderId} href="/admin/mis-ventas" className="grid grid-cols-[1fr_auto] gap-2 py-3 text-sm"><span><strong className="block">{sale.customerName}</strong><span className="text-xs text-black/50">{sale.orderNumber}</span></span><span className="text-right"><strong>{formatCurrency(sale.total)}</strong><span className="block text-xs text-emerald-700">{sale.commissionStatus?commissionStatusLabels[sale.commissionStatus]:"Sin comision"}</span></span></Link>)}{!data.recentSales.length?<p className="py-5 text-center text-sm text-black/45">Tus ventas apareceran aqui.</p>:null}</div></article></div>
      <article className="rounded-xl border border-black/10 bg-white p-3 shadow-sm"><div className="flex items-center gap-2"><Tag size={18}/><h2 className="font-semibold">Solicitudes de precio</h2></div><div className="mt-3 grid grid-cols-3 gap-2 text-center"><div className="rounded-lg bg-amber-50 p-2"><strong>{data.priceRequests.pending}</strong><span className="block text-xs">Pendientes</span></div><div className="rounded-lg bg-emerald-50 p-2"><strong>{data.priceRequests.approvedRecently}</strong><span className="block text-xs">Aprobadas</span></div><div className="rounded-lg bg-red-50 p-2"><strong>{data.priceRequests.rejectedRecently}</strong><span className="block text-xs">Rechazadas</span></div></div><div className="mt-2 divide-y">{data.priceRequests.recent.map(request=><div key={request.requestId} className="flex justify-between gap-2 py-3 text-sm"><span><strong className="block">{request.productName}</strong><span className="text-xs text-black/50">{request.sku}</span></span><span className="text-right"><strong>{formatCurrency(request.requestedPrice)}</strong><span className="block text-xs">{request.status}</span></span></div>)}</div></article>
      <div className="space-y-3"><QuickSearch title="Buscar cliente" icon={UserRound} value={customerQuery} onChange={setCustomerQuery} onSearch={searchCustomers} busy={customerBusy} placeholder="Nombre, telefono o RTN">{customers.map(customer=><Link key={customer.customerId} href={`/admin/clientes?customerId=${customer.customerId}`} className="block rounded-lg border p-3 text-sm"><strong>{customer.displayName}</strong><span className="block text-xs text-black/50">{customer.phoneMasked}</span></Link>)}</QuickSearch><QuickSearch title="Consultar producto" icon={Package} value={productQuery} onChange={setProductQuery} onSearch={searchProducts} busy={productBusy} placeholder="Nombre, SKU o codigo">{products.map(product=><Link key={product.productId} href={`/admin/productos?q=${encodeURIComponent(product.sku)}`} className="grid grid-cols-[1fr_auto] rounded-lg border p-3 text-sm"><span><strong className="block">{product.name}</strong><span className="text-xs text-black/50">{product.sku}</span></span><span className="text-right"><span className="block text-xs text-emerald-700">Disponible: {product.availableStock??"Sin limite"}</span><strong>{formatCurrency(product.authorizedPrice)}</strong></span></Link>)}</QuickSearch></div>
    </section>
  </main>;
}

function QuickSearch({title,icon:Icon,value,onChange,onSearch,busy,placeholder,children}:{title:string;icon:typeof Search;value:string;onChange:(value:string)=>void;onSearch:()=>void;busy:boolean;placeholder:string;children:React.ReactNode}){return <article className="rounded-xl border border-black/10 bg-white p-3 shadow-sm"><div className="flex items-center gap-2"><Icon size={18}/><h2 className="font-semibold">{title}</h2></div><label className="mt-3 block text-xs font-semibold">Busqueda<span className="mt-1 flex gap-2"><input value={value} onChange={event=>onChange(event.target.value)} onKeyDown={event=>{if(event.key==="Enter")onSearch();}} placeholder={placeholder} className="min-h-11 min-w-0 flex-1 rounded-lg border px-3 text-sm font-normal"/><button type="button" onClick={onSearch} disabled={busy} className="inline-flex min-h-11 items-center gap-2 rounded-lg border px-3 text-sm"><Search size={17}/>{busy?"...":"Buscar"}</button></span></label><div className="mt-2 space-y-2">{children}</div></article>}
