import type { AdminInvoiceDetail, StoreInvoice } from "@/types/invoices";
import type { OfficialInvoiceInput } from "@/utils/official-invoice-document";

export function adminInvoiceToOfficialInvoice(invoice: AdminInvoiceDetail): OfficialInvoiceInput {
  return {
    invoiceNumber: invoice.invoice_number,
    orderNumber: invoice.order_number,
    status: invoice.status,
    issuedAt: invoice.issued_at,
    invoiceDate: invoice.invoice_date,
    dueAt: invoice.due_at,
    createdAt: invoice.created_at,
    companyLegalName: invoice.company_legal_name,
    companyRtn: invoice.company_rtn ?? invoice.rtn,
    companyAddress: invoice.company_address,
    companyPhone: invoice.company_phone,
    companyEmail: invoice.company_email,
    companyLogoUrl: invoice.company_logo_url,
    cai: invoice.cai,
    fiscalRangeStart: invoice.fiscal_range_start,
    fiscalRangeEnd: invoice.fiscal_range_end,
    caiAuthorizationDate: invoice.cai_authorization_date,
    fiscalDeadline: invoice.due_at,
    customerName: invoice.customer_name,
    customerRtn: invoice.customer_rtn,
    customerEmail: invoice.customer_email,
    customerPhone: invoice.customer_phone,
    customerAddress: invoice.customer_address,
    paymentMethod: invoice.payment_method,
    paymentStatus: invoice.payment_status,
    paymentReference: invoice.bank_reference_number,
    transferReceiptUrl: invoice.transfer_receipt_url,
    subtotal: invoice.subtotal,
    tax: invoice.tax,
    shippingFee: invoice.shipping_fee,
    cashOnDeliveryFee: invoice.cash_on_delivery_fee,
    smallOrderFee: invoice.small_order_fee,
    discountTotal: invoice.discount_total,
    additionalFees: invoice.additional_fees,
    total: invoice.total,
    items: invoice.items.map((item) => ({
      sku: item.sku,
      name: item.product_name,
      quantity: item.quantity,
      unitPrice: item.unit_price,
      lineTotal: item.line_total,
    })),
  };
}

export function storeInvoiceToOfficialInvoice(invoice: StoreInvoice): OfficialInvoiceInput {
  return {
    invoiceNumber: invoice.invoiceNumber,
    orderNumber: invoice.orderNumber,
    status: invoice.status,
    issuedAt: invoice.issuedAt,
    invoiceDate: invoice.invoiceDate,
    dueAt: invoice.fiscalDeadline,
    createdAt: invoice.issuedAt,
    companyLegalName: invoice.companyLegalName,
    companyRtn: invoice.companyRtn ?? invoice.rtn,
    companyAddress: invoice.companyAddress,
    companyPhone: invoice.companyPhone,
    companyEmail: invoice.companyEmail,
    companyLogoUrl: invoice.companyLogoUrl,
    cai: invoice.cai,
    fiscalRangeStart: invoice.fiscalRangeStart,
    fiscalRangeEnd: invoice.fiscalRangeEnd,
    caiAuthorizationDate: invoice.caiAuthorizationDate,
    fiscalDeadline: invoice.fiscalDeadline,
    customerName: invoice.customerName,
    customerRtn: invoice.customerRtn,
    customerEmail: invoice.customerEmail,
    customerPhone: invoice.customerPhone,
    customerAddress: invoice.customerAddress,
    paymentMethod: invoice.paymentMethod,
    paymentStatus: null,
    paymentReference: invoice.paymentReference,
    subtotal: invoice.subtotal,
    tax: invoice.isv,
    shippingFee: invoice.shippingFee,
    cashOnDeliveryFee: invoice.cashOnDeliveryFee,
    smallOrderFee: invoice.smallOrderFee,
    discountTotal: invoice.discountTotal,
    additionalFees: invoice.additionalFees,
    total: invoice.total,
    items: invoice.items.map((item) => ({
      sku: item.sku,
      name: item.name,
      quantity: item.quantity,
      unitPrice: item.unitPrice,
      lineTotal: item.lineTotal,
    })),
  };
}
