import Link from "next/link";
import { Plus } from "lucide-react";
import { AdminBackButton } from "@/components/admin/admin-back-button";
import { AdminShell } from "@/components/admin/admin-shell";
import { hasEffectivePermission } from "@/lib/auth/permissions";
import { requirePermission } from "@/lib/auth/session";
import { getInventoryAdjustments } from "@/services/supabase/inventory-adjustments.service";
import { formatHnDateTime } from "@/utils/format";

export const dynamic = "force-dynamic";
const statusLabel: Record<string,string>={draft:"Borrador",confirmed:"Confirmado",cancelled:"Cancelado",reversed:"Revertido"};
const typeLabel: Record<string,string>={increase:"Incremento",decrease:"Disminución",mixed:"Mixto"};

export default async function InventoryAdjustmentsPage({searchParams}:{searchParams:Promise<{q?:string;status?:string;from?:string;to?:string;page?:string}>}){
  const profile=await requirePermission("inventory:adjust_read"); const params=await searchParams;
  const canCreate=hasEffectivePermission(profile.role,profile.permissions,"inventory:adjust_create",profile.email);
  const canCost=hasEffectivePermission(profile.role,profile.permissions,"inventory:cost_read",profile.email);
  const page=Math.max(Number(params.page)||1,1); const pageSize=50;
  const result=await getInventoryAdjustments({query:params.q,status:params.status,from:params.from,to:params.to,page,pageSize});
  return <AdminShell title="Ajustes de inventario"><AdminBackButton/><div className="space-y-5">
    <nav aria-label="Secciones de inventario" className="flex flex-wrap gap-2"><Link href="/admin/inventario" className="min-h-11 rounded-lg border border-black/10 px-4 py-2.5 text-sm font-semibold">Inventario general</Link><Link href="/admin/inventario/ajustes" aria-current="page" className="min-h-11 rounded-lg bg-black px-4 py-2.5 text-sm font-semibold text-white">Historial de ajustes</Link>{canCreate?<Link href="/admin/inventario/ajustes/nuevo" className="inline-flex min-h-11 items-center gap-2 rounded-lg bg-[#e4252c] px-4 py-2.5 text-sm font-semibold text-white"><Plus aria-hidden size={17}/>Crear ajuste</Link>:null}</nav>
    <section className="rounded-xl border border-black/10 bg-white p-4"><form className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><label><span className="mb-1 block text-xs font-medium uppercase text-black/50">Buscar</span><input name="q" defaultValue={params.q} placeholder="Número, usuario o referencia" className="min-h-11 w-full rounded-lg border border-black/15 px-3"/></label><label><span className="mb-1 block text-xs font-medium uppercase text-black/50">Estado</span><select name="status" defaultValue={params.status??""} className="min-h-11 w-full rounded-lg border border-black/15 px-3"><option value="">Todos</option>{Object.entries(statusLabel).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label><span className="mb-1 block text-xs font-medium uppercase text-black/50">Desde</span><input name="from" type="date" defaultValue={params.from} className="min-h-11 w-full rounded-lg border border-black/15 px-3"/></label><label><span className="mb-1 block text-xs font-medium uppercase text-black/50">Hasta</span><input name="to" type="date" defaultValue={params.to} className="min-h-11 w-full rounded-lg border border-black/15 px-3"/></label><button type="submit" className="min-h-11 self-end rounded-lg bg-black px-4 font-semibold text-white">Aplicar filtros</button></form></section>
    <section className="overflow-hidden rounded-xl border border-black/10 bg-white"><div className="border-b border-black/10 p-4 sm:p-5"><h2 className="font-semibold">Historial</h2><p className="text-sm text-black/50">{result.total.toLocaleString("es-HN")} documentos</p></div>
      <div className="grid gap-3 p-3 md:hidden">{result.items.map(item=><article key={item.id} className="rounded-lg border border-black/10 p-4"><div className="flex justify-between gap-3"><div><Link href={`/admin/inventario/ajustes/${item.id}`} className="font-semibold underline-offset-4 hover:underline">{item.adjustment_number}</Link><p className="text-xs text-black/50">{item.effective_date}</p></div><span className="h-fit rounded-full bg-[#f4f4f5] px-2.5 py-1 text-xs font-semibold">{statusLabel[item.status]}</span></div><dl className="mt-4 grid grid-cols-2 gap-2 text-sm"><Mini label="Tipo" value={typeLabel[item.type]}/><Mini label="Productos" value={String(item.line_count)}/><Mini label="Unidades" value={`+${item.increase_quantity} / -${item.decrease_quantity}`}/><Mini label="Contabilidad" value={item.accounting_status==="pending_mapping"?"Mapeo pendiente":item.accounting_status}/>{canCost?<Mini label="Valor" value={`L ${(item.total_cost??0).toLocaleString("es-HN",{minimumFractionDigits:2})}`}/>:null}</dl><p className="mt-3 break-words text-sm text-black/60">{item.reference||"Sin referencia"} · {item.actor_name}</p></article>)}{!result.items.length?<p className="p-4 text-sm text-black/50">No hay ajustes con esos filtros.</p>:null}</div>
      <div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-[#e7e5e4] text-xs uppercase text-black/55"><tr>{["Número","Fecha efectiva","Creado / confirmado","Estado","Productos","Tipo / unidades","Referencia","Usuario","Contabilidad",...(canCost?["Valor"]:[]),"Acción"].map(h=><th key={h} className="px-3 py-3">{h}</th>)}</tr></thead><tbody className="divide-y divide-black/10">{result.items.map(item=><tr key={item.id}><td className="px-3 py-3 font-semibold">{item.adjustment_number}</td><td className="px-3 py-3">{item.effective_date}</td><td className="px-3 py-3"><span className="block">{formatHnDateTime(item.created_at)}</span>{item.confirmed_at?<span className="text-xs text-black/45">{formatHnDateTime(item.confirmed_at)}</span>:null}</td><td className="px-3 py-3">{statusLabel[item.status]}</td><td className="px-3 py-3">{item.line_count}</td><td className="px-3 py-3">{typeLabel[item.type]}<span className="block text-xs text-black/50">+{item.increase_quantity} / -{item.decrease_quantity}</span></td><td className="max-w-48 break-words px-3 py-3">{item.reference||"-"}</td><td className="px-3 py-3">{item.actor_name}</td><td className="px-3 py-3">{item.accounting_status==="pending_mapping"?"Mapeo pendiente":item.accounting_status}</td>{canCost?<td className="px-3 py-3">L {(item.total_cost??0).toLocaleString("es-HN",{minimumFractionDigits:2})}</td>:null}<td className="px-3 py-3"><Link href={`/admin/inventario/ajustes/${item.id}`} className="inline-flex min-h-11 items-center rounded-lg border border-black/15 px-3 font-semibold">Ver detalle</Link></td></tr>)}</tbody></table></div>
      <div className="flex items-center justify-between border-t border-black/10 p-4"><span className="text-sm text-black/50">Página {page}</span><div className="flex gap-2">{page>1?<Link href={{pathname:"/admin/inventario/ajustes",query:{...params,page:page-1}}} className="min-h-11 rounded-lg border px-4 py-2.5">Anterior</Link>:null}{page*pageSize<result.total?<Link href={{pathname:"/admin/inventario/ajustes",query:{...params,page:page+1}}} className="min-h-11 rounded-lg border px-4 py-2.5">Siguiente</Link>:null}</div></div>
    </section>
  </div></AdminShell>;
}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-md bg-[#f8fafc] p-2"><dt className="text-xs text-black/45">{label}</dt><dd className="font-semibold">{value}</dd></div>}
